const Menu = [
	{
		id: 1,
		image: "soemhtinv",
		name: "maggi",
		category: "breakfast",
		price: "Rs. 12",
		description: "njndvnfjvf",
	},
	{
		id: 2,
		image: "soemhtinv",
		name: "allu pakoda",
		category: "evening",
		price: "Rs. 20",
		description: "njndvnfjvf",
	},
	{
		id: 3,
		image: "soemhtinv",
		name: "corn",
		category: "breakfast",
		price: "Rs. 10",
		description: "njndvnfjvf",
	},
	{
		id: 4,
		image: "soemhtinv",
		name: "chola",
		category: "lunch",
		price: "Rs. 50",
		description: "njndvnfjvf",
	},
	{
		id: 5,
		image: "soemhtinv",
		name: "pizza",
		category: "evening",
		price: "Rs. 80",
		description: "njndvnfjvf",
	},
	{
		id: 6,
		image: "soemhtinv",
		name: "non-veg thali",
		category: "dinner",
		price: "Rs. 180",
		description: "njndvnfjvf",
	},
	{
		id: 7,
		image: "soemhtinv",
		name: "samosa",
		category: "evening",
		price: "Rs. 10",
		description: "njndvnfjvf",
	},
	{
		id: 8,
		image: "soemhtinv",
		name: "rajma rice",
		category: "lunch",
		price: "Rs. 60",
		description: "njndvnfjvf",
	},
	{
		id: 9,
		image: "soemhtinv",
		name: "sweets",
		category: "dinner",
		price: "Rs. 60",
		description: "njndvnfjvf",
	},
];

export default Menu;
